services:
  bewoning-informatie-service:
    container_name: bewoning-informatie-service
    image: ghcr.io/brp-api/bewoning-informatie-service:latest
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ASPNETCORE_URLS=http://+:5000
      - Ecs__Path=/var/log/bewoning-informatie-service.json
      - Ecs__SecuredPath=/var/log/bewoning-informatie-service-secured.json
      - Routes__0__DownstreamScheme=http
      - Routes__0__DownstreamHostAndPorts__0__Host=bewoning-data-service
      - Routes__0__DownstreamHostAndPorts__0__Port=80
    ports:
      - "5000:5000"
    volumes:
      - ../test-data/logs:/var/log
    networks:
      - brp-api-network

networks:
  brp-api-network:
    name: brp-api-network
